title: Jackson H. Oechsle
logo: docs/assets/Headshot.png
description: |
  Computer science senior focusing in cybersecurity with experience in software development, exploit engineering, and system security analysis. Seeking full-time position in May 2026 in cybersecurity, national defense, law enforcement, and other public service organizations.
theme: jekyll-theme-minimal
